image: mesosphere/aws-cli:1.14.5

pipelines:
  branches:
    custom:
      run-tests:
      - step:
            name: Run Firefox Tests
            image: pgesek/maven-geckodriver:1.0
            caches: 
            - maven
            script:
            - cd ui-tests && mvn clean test -Dbrowser=firefox -Dwebdriver.gecko.driver=/usr/bin/geckodriver -Dheadless=true

